# Generated by Django 3.1.5 on 2021-01-08 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'позиция',
                'verbose_name_plural': 'Инвентарь',
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('order_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'кальян',
                'verbose_name_plural': 'Кальяны',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('adres', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('second_name', models.CharField(blank=True, max_length=40)),
                ('mobile_phone', models.CharField(blank=True, default='+375()', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('start_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_open', models.BooleanField(default=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.place')),
                ('profile', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='data.profile')),
            ],
            options={
                'verbose_name': 'смена',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.item')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.place')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session')),
            ],
            options={
                'verbose_name': 'инвентарь',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ordertype')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
