# Generated by Django 3.1.5 on 2021-01-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
