# Generated by Django 3.1.5 on 2021-01-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210108_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
