# Generated by Django 3.1.5 on 2021-01-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210110_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
